version: '3.9'

services:

  db:
    image: postgres:16.2-bullseye # we are using specific bullseye image for minimal DB size
    restart: always
    container_name: dads_db
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: dad_pass
      POSTGRES_DB: dad
      POSTGRES_USER: dad_user
    volumes:
      - type: bind
        source: ./pgdata
        target: /var/lib/postgresql
      # - ./pgdata:/var/lib/postgresql
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - backend_network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: always
    container_name: dads_backend
    ports:
      - 5000:5000
    networks:
      - frontend_network
      - backend_network
    depends_on:
      - db
    expose:
      - 5000

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    restart: always
    container_name: dads_frontend
    ports:
      - 3000:3000
    networks:
      - frontend_network
      - backend_network
    expose:
      - 3000
    depends_on:
      - db
      - backend

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./pgdata

networks:
  backend_network:
  frontend_network: